method: nice
dataset: 'ocam_panorama'
occupancy: False
data:
  input_folder: /data/chsung/201029_coex_s9
  # input_folder: /data/multipleye/201029_coex_s9
  output: output/tmp_exp/tmp49_add_fusion_linear_nice_density_N_importance_small_add_histogram_thresh_10
  config_file: config.yaml
  poses_file: trajectory_no_dynamic_lidar_large.txt
grid_len:
  coarse: 2 
  middle: 0.32 
  fine: 0.16
  color: 0.16
  bound_divisable: 0.32
pretrained_decoders:
  use: False
meshing:
  level_set: 10
  resolution: 512 # change to 512 for higher resolution geometry
  clean_mesh: False
mapping:
  device: "cuda:0"
  BA: False
  middle_iter_ratio: 0.3
  fine_iter_ratio: 0.5
  every_frame: 1
  vis_freq: 1
  vis_inside_freq: 10
  mesh_freq: 1
  ckpt_freq: 10
  keyframe_every: 1
  mapping_window_size: 10.0
  # marching_cubes_bound: [[-1.0, 1.0], [-1.0, 1.0], [-1.0, 1.0]] 
  frustum_feature_selection: False
  pixels: 5000
  iters_first: 10
  iters: 100
  # bound: [[-25.0, 60.0], [-5.0, 2.0], [-60.0, 25.0]]
  # bound: [[-33.0, 28.0], [-5.0, 2.0], [-23.0, 26.0]]
  # bound: [[-20.0, 20.0], [-5.0, 2.0], [-20.0, 20.0]]
  # bound: [[-33.0, 20.0], [-3.0, 2.0], [-20.0, 30.0]] # middle
  bound: [[-20.0, 30.0], [-3.0, 2.0], [-30.0, 20.0]] # small
  # bound: [[-1.0, 1.0], [-1.0, 1.0], [-1.0, 1.0]] 
  # marching_cubes_bound: [[-25.0, 60.0], [-5.0, 2.0], [-60.0, 25.0]]
  # marching_cubes_bound: [[-33.0, 28.0], [-5.0, 2.0], [-23.0, 26.0]]
  # marching_cubes_bound: [[-33.0, 20.0], [-3.0, 2.0], [-20.0, 30.0]]
  marching_cubes_bound: [[-20.0, 20.0], [-3.0, 2.0], [-20.0, 20.0]] 
  no_vis_on_first_frame: False
  stage:
    middle:
      decoders_lr: 0.005
    fine:
      decoders_lr: 0.005
    color:
      decoders_lr: 0.005
cam:
  H: 160
  W: 640
  crop_edge: 0
  method: 'panorama'
  phi_deg: -45.0
  phi_max_deg: 45.0
omnimvs:
  device: "cuda:1"
  config_file: config.yaml
  network_type: default
  snapshot_path: pretrained/omnimvs/full3-2x-rgb-reflect2_42.pt
  dbname: 201029_coex_s9
  db_root: /data/chsung
  # db_root: /data/multipleye
  db_config_idxs: []
  resp_volume_freeze: True
  lr: 0.000
  omnimvs_opts:
    poses_file: trajectory_no_dynamic_lidar_small.txt
    step: 5
    phi_deg: -45
    phi_max_deg: 45
    num_invdepth: 192
    equirect_size: [160, 640]
    out_cost: True
    lt_equirect_sample_ratio: 1
    lt_depth_sample_ratio: 2
  net_opts:
    CH: 32
    circular_pad: True
    upsample: False
    use_rgb: True
rendering:
  N_samples: 64
  N_surface: 32
  N_importance: 32
  lindisp: False
  perturb: 0.0
model:
  c_dim: 32