dataset: 'ocam_perspective'
data:
  input_folder: /data/multipleye/201029_coex_s9
  output: output/Omni/201029_coex_s9_19_tmp
grid_len:
  coarse: 2 
  middle: 0.32 
  fine: 0.16
  color: 0.16
  bound_divisable: 0.32
tracking:
  vis_freq: 50
  vis_inside_freq: 25
  ignore_edge_W: 20
  ignore_edge_H: 20
  seperate_LR: True
  const_speed_assumption: False
  no_vis_on_first_frame: False
  gt_camera: True
  lr: 0.0005
  pixels: 1000
  iters: 50
mapping:
  BA: False
  middle_iter_ratio: 0.4
  fine_iter_ratio: 0.4
  every_frame: 1
  vis_freq: 1
  vis_inside_freq: 10
  mesh_freq: 10
  ckpt_freq: 10
  keyframe_every: 1
  mapping_window_size: 10
  pixels: 2000
  iters_first: 500
  iters: 300
  # bound: [[-33.0, 28.0], [-5.0, 2.0], [-23.0, 26.0]]
  bound: [[-14.0, 10.0], [-5.0, 2.0], [-15.0, 10.0]] 
  # marching_cubes_bound: [[-33.0, 28.0], [-5.0, 2.0], [-23.0, 26.0]]
  marching_cubes_bound: [[-14.0, 10.0], [-5.0, 2.0], [-15.0, 10.0]] 
  no_vis_on_first_frame: False
cam:
  H: 264
  W: 416
  fx: 108.01766298948733
  fy: 121.0972625615004
  cx: 207.5
  cy: 131.5
  crop_edge: 0
rendering:
  N_samples: 128
  N_surface: 64
  N_importance: 0
  lindisp: False
  perturb: 0.0
model:
  c_dim: 32