dataset: 'ocam_panorama'
data:
  input_folder: /data/chsung/201029_coex_s9
  # input_folder: /data/multipleye/201029_coex_s9
  output: output/tmp_exp/tmp35_add_fusion_linear_use_pretrain_seerslab
  config_file: config.yaml
  poses_file: trajectory_no_dynamic_lidar_large.txt
grid_len:
  coarse: 1
  middle: 0.25
  fine: 0.10
  color: 0.10
  bound_divisable: 0.25
meshing:
  level_set: 0
  resolution: 0.04 # change to 512 for higher resolution geometry
mapping:
  device: "cuda:2"
  BA: False
  middle_iter_ratio: 0.3
  fine_iter_ratio: 0.5
  every_frame: 1
  vis_freq: 1
  vis_inside_freq: 10
  mesh_freq: 1
  ckpt_freq: 10
  keyframe_every: 1
  mapping_window_size: 10
  frustum_feature_selection: False
  pixels: 5000
  iters_first: 10
  iters: 100
  bound: [[-25.0, 20.0], [-2.0, 2.0], [-40.0, 20.0]]
  marching_cubes_bound: [[-25.0, 20.0], [-2.0, 2.0], [-40.0, 20.0]]
  no_vis_on_first_frame: False
  stage:
    middle:
      decoders_lr: 0.005
    fine:
      decoders_lr: 0.005
    color:
      decoders_lr: 0.005
cam:
  H: 160
  W: 640
  crop_edge: 0
  method: 'panorama'
  phi_deg: -45.0
  phi_max_deg: 45.0
omnimvs:
  device: "cuda:3"
  config_file: config.yaml
  network_type: default
  snapshot_path: pretrained/omnimvs/full3-2x-rgb-reflect2_42.pt
  dbname: 211021_seerslab
  db_root: /data/chsung
  # db_root: /data/multipleye
  db_config_idxs: []
  resp_volume_freeze: False
  lr: 0.000
  omnimvs_opts:
    poses_file: trajectory_small.txt
    step: 3
    phi_deg: -45
    phi_max_deg: 45
    num_invdepth: 192
    equirect_size: [160, 640]
    out_cost: True
    lt_equirect_sample_ratio: 1
    lt_depth_sample_ratio: 2
  net_opts:
    CH: 32
    circular_pad: True
    upsample: False
    use_rgb: True
rendering:
  N_samples: 128
  N_surface: 64
  N_importance: 0
  lindisp: False
  perturb: 0.0
model:
  c_dim: 32