dataset: 'ocam_panorama'
data:
  # input_folder: /data/chsung/201029_coex_s9
  input_folder: /data/chsung/211021_seerslab
  output: output/Omni_panorama/211021_seerslab_small_2_dense
  config_file: capture.yaml
  poses_file: trajectory_small.txt
grid_len:
  coarse: 1
  middle: 0.25
  fine: 0.10
  color: 0.10
  bound_divisable: 0.25
meshing:
  level_set: 0
  resolution: 0.04 # change to 512 for higher resolution geometry
tracking:
  vis_freq: 50
  vis_inside_freq: 25
  ignore_edge_W: 20
  ignore_edge_H: 20
  seperate_LR: True
  const_speed_assumption: False
  no_vis_on_first_frame: False
  gt_camera: True
  lr: 0.0005
  pixels: 1000
  iters: 50
mapping:
  device: "cuda:1"
  BA: False
  middle_iter_ratio: 0.4
  fine_iter_ratio: 0.6
  every_frame: 1
  vis_freq: 1
  vis_inside_freq: 100
  mesh_freq: 2
  ckpt_freq: 2
  keyframe_every: 1
  mapping_window_size: 10
  frustum_feature_selection: False
  pixels: 5000
  iters_first: 1000
  iters: 1000
  bound: [[-25.0, 20.0], [-2.0, 2.0], [-40.0, 20.0]]
  marching_cubes_bound: [[-25.0, 20.0], [-2.0, 2.0], [-40.0, 20.0]]
  no_vis_on_first_frame: False
cam:
  H: 160
  W: 640
  crop_edge: 0
  method: 'panorama'
  phi_deg: -45.0
  phi_max_deg: 45.0
rendering:
  N_samples: 128
  N_surface: 64
  N_importance: 0
  lindisp: False
  perturb: 0.0
model:
  c_dim: 32