method: nice
dataset: 'ocam_panorama'
occupancy: True
data:
  # input_folder: /data/chsung/under_parking_seq
  input_folder: /data5/chnagho/data/under_parking_seq
  output: /data5/changho/nice-slam/output/underparking_sparse_frag/61_nice_occ_600_geo_feat_multiplyProb_use_pretrain_variance_48_16_localfrag_normalizePoints_concatMean_sameDimBound_singleFeatureNet_wColor_concatDir_realColorVal_appendColors_onlyColorinMLP_newColorMLPv2_concatGeoFeat
  config_file: capture.yaml
  poses_file: trajectory.txt
grid_len:
  coarse: 2
  middle: 0.32
  fine: 0.16
  color: 0.16
  bound_divisable: 0.32
  vol_dim: [96, 48, 96]
pretrained_decoders:
  use: True
meshing:
  level_set: 0
  resolution: 0.04 # change to 512 for higher resolution geometry
  device: "cuda:1"
  clean_mesh: True
mapping:
  device: "cuda:1"
  BA: False
  middle_iter_ratio: 0.0
  fine_iter_ratio: 1.0
  every_frame: 1
  vis_freq: 1
  vis_inside_freq: 1
  mesh_freq: 1
  ckpt_freq: 1
  keyframe_every: 1
  mapping_window_size: 10
  frustum_feature_selection: False
  pixels: 7500
  iters_first: 10
  iters: 50
  joint_iters: 5
  w_color_loss: 1
  w_geo_loss: 1
  bound: [[-5.0, 4.0], [-2.0, 2.0], [-5.0, 10.0]] # 표지판(~65)
  marching_cubes_bound: [[-5.0, 4.0], [-2.0, 2.0], [-5.0, 10.0]] # 표지판(~65)
  no_vis_on_first_frame: False
  stage:
    middle:
      middle_decoder_lr: 0.0
      fine_decoder_lr: 0.0
      color_decoder_lr: 0.0
      grufusion_lr: 0.0
      costfusion_lr:
        middle: 0.001
        fine: 0.0
        color: 0.0
      featnet_lr: 0.001
    fine:
      middle_decoder_lr: 0.0
      fine_decoder_lr: 0.0
      color_decoder_lr: 0.0
      grufusion_lr: 0.0
      costfusion_lr:
        middle: 0.0005
        fine: 0.0005
        color: 0.0
      featnet_lr: 0.001
    color:
      middle_decoder_lr: 0.0000001
      fine_decoder_lr: 0.0000001
      color_decoder_lr: 0.001
      grufusion_lr: 0.0
      costfusion_lr:
        middle: 0.0000001
        fine: 0.0000001
        color: 0.001
      featnet_lr: 0.001
cam:
  H: 160
  W: 640
  crop_edge: 0
  method: 'panorama'
  phi_deg: -45.0
  phi_max_deg: 45.0
omnimvs:
  device: "cuda:1"
  config_file: config.yaml
  network_type: default
  snapshot_path: pretrained/omnimvs/full3-2x-rgb-reflect2_42.pt
  dbname: under_parking_seq
  db_root: /data5/changho/data
  db_config_idxs: []
  resp_volume_freeze: True
  net_freeze: False
  lr: 0.0001
  n_frames: 10
  dist_bound: 5.0
  omnimvs_opts:
    poses_file: trajectory_600.txt
    dtype:
    step: 1
    phi_deg: -45
    phi_max_deg: 45
    num_invdepth: 192
    equirect_size: [160, 640]
    out_cost: True
    lt_equirect_sample_ratio: 1
    lt_depth_sample_ratio: 2
  net_opts:
    CH: 32
    circular_pad: True
    upsample: False
    use_rgb: True
rendering:
  N_samples: 128
  N_surface: 48
  N_importance: 16
  lindisp: False
  perturb: 0.0
model:
  c_dim: 32
  fusion_method: variance
  pos_embedding_method: nerf
  convgru_ks: 1
  feature_fusion: False
  train_continue: False
  finetune: False
  ckpt_path: /data5/changho/nice-slam/output/underparking_sparse_frag/54_nice_sdf_600_geo_feat_multiplyProb_use_pretrain_variance_48_16_localfrag_normalizePoints_concatMean_sameDimBound_singleFeatureNet_wColor_concatDir_realColorVal_append10Colors_onlyColorinMLP_withoutDir/ckpts/00000.tar