method: imap
coarse: False
sync_method: strict
scale: 1
dataset: 'ocam_panorama'
occupancy: False
data:
  input_folder: /data/chsung/under_parking_seq
  # input_folder: /data/multipleye/201029_coex_s9
  # output: output/tmp/tmp1
  # output: output/tmp_exp/tmp_original2
  # output: output/Omni_panorama/underparking_all_5_debug
  output: output/new_underparking_tmp/restore/02_imap_restore
  config_file: capture.yaml
  poses_file: trajectory_small.txt
grid_len:
  coarse: 2 
  middle: 0.32 
  fine: 0.16
  color: 0.16
  bound_divisable: 0.32
meshing:
  level_set: 10
  resolution: 0.04 # change to 512 for higher resolution geometry
  device: "cuda:3"
  color_mesh_extraction_method: render_ray_along_normal
tracking:
  gt_camera: True
mapping:
  device: "cuda:2"
  BA: False
  middle_iter_ratio: 0.4
  fine_iter_ratio: 0.6
  every_frame: 1
  vis_freq: 1
  vis_inside_freq: 100
  mesh_freq: 10
  ckpt_freq: 10
  keyframe_every: 1
  mapping_window_size: 10
  frustum_feature_selection: False
  keyframe_selection_method: 'global'
  pixels: 7000
  iters_first: 1000
  iters: 1000
  # bound: [[-24.0, 37.0], [-5.0, 2.0], [-9.0, 63.0]] 
  # marching_cubes_bound: [[-24.0, 37.0], [-5.0, 2.0], [-9.0, 63.0]] 
  bound: [[-16.0, 24.0], [-3.0, 2.0], [-9.0, 34.0]] # small
  marching_cubes_bound: [[-16.0, 24.0], [-3.0, 2.0], [-9.0, 34.0]] # small
  no_vis_on_first_frame: False
  imap_decoders_lr: 0.0002
cam:
  H: 320
  W: 640
  crop_edge: 0
  method: 'panorama'
  phi_deg: -90.0
  phi_max_deg: 90.0
# rendering:
#   N_samples: 64
#   N_surface: 0
#   N_importance: 12
#   lindisp: False
#   perturb: 0.0
model:
  c_dim: 32
  feature_fusion: False