method: nice
dataset: 'ocam_panorama'
occupancy: True
data:
  input_folder: /data/chsung/under_parking_seq
  # input_folder: /data/multipleye/201029_coex_s9
  # output: output/tmp/tmp1
  # output: output/tmp_exp/tmp_original2
  # output: output/Omni_panorama/underparking_all_5_debug
  output: output/new_underparking_tmp/restore/1_nice_restore
  config_file: capture.yaml
  poses_file: trajectory_small.txt
grid_len:
  coarse: 2 
  middle: 0.32 
  fine: 0.16
  color: 0.16
  bound_divisable: 0.32
pretrained_decoders:
  use: True
meshing:
  level_set: 0
  resolution: 0.04 # change to 512 for higher resolution geometry
  device: "cuda:1"
tracking:
  vis_freq: 50
  vis_inside_freq: 25
  ignore_edge_W: 20
  ignore_edge_H: 20
  seperate_LR: True
  const_speed_assumption: False
  no_vis_on_first_frame: False
  gt_camera: True
  lr: 0.0005
  pixels: 1000
  iters: 50
mapping:
  device: "cuda:0"
  BA: False
  middle_iter_ratio: 0.4
  fine_iter_ratio: 0.6
  every_frame: 1
  vis_freq: 1
  vis_inside_freq: 100
  mesh_freq: 10
  ckpt_freq: 10
  keyframe_every: 1
  mapping_window_size: 10
  frustum_feature_selection: False
  pixels: 7000
  iters_first: 1000
  iters: 1000
  # bound: [[-24.0, 37.0], [-5.0, 2.0], [-9.0, 63.0]] 
  # marching_cubes_bound: [[-24.0, 37.0], [-5.0, 2.0], [-9.0, 63.0]] 
  bound: [[-16.0, 24.0], [-3.0, 2.0], [-9.0, 34.0]] # small
  marching_cubes_bound: [[-16.0, 24.0], [-3.0, 2.0], [-9.0, 34.0]] # small
  no_vis_on_first_frame: False
  imap_decoders_lr: 0.0002
cam:
  H: 320
  W: 640
  crop_edge: 0
  method: 'panorama'
  phi_deg: -90.0
  phi_max_deg: 90.0
omnimvs:
  device: "cuda:1"
  config_file: config.yaml
  network_type: default
  snapshot_path: pretrained/omnimvs/full3-2x-rgb-reflect2_42.pt
  dbname: 201029_coex_s9
  db_root: /data/chsung
  # db_root: /data/multipleye
  db_config_idxs: []
  resp_volume_freeze: True
  net_freeze: False
  lr: 0.0001
  omnimvs_opts:
    poses_file: trajectory_no_dynamic_lidar_small.txt
    step: 5
    phi_deg: -45
    phi_max_deg: 45
    num_invdepth: 192
    equirect_size: [160, 640]
    out_cost: True
    lt_equirect_sample_ratio: 1
    lt_depth_sample_ratio: 2
  net_opts:
    CH: 32
    circular_pad: True
    upsample: False
    use_rgb: True
rendering:
  N_samples: 128
  N_surface: 64
  N_importance: 0
  lindisp: False
  perturb: 0.0
model:
  c_dim: 32
  feature_fusion: False